# kubernetes/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  # Generate with: echo -n 'your-secret-key-here' | base64
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=
  # Generate with: echo -n 'postgres://user:pass@postgres:5432/db' | base64
  database-url: cG9zdGdyZXM6Ly91c2VyOnBhc3NAcG9zdGdyZXM6NTQzMi9kYg==
  